import type { Lesson, Concept, Module, Quiz } from '@/types'

// ─── Concepts ─────────────────────────────────────────────────────────────────

export const MOCK_CONCEPTS: Concept[] = [
  {
    id: 'c-trail-braking',
    slug: 'trail-braking',
    title: 'Trail Braking',
    summary: 'Carrying brake pressure past the turn-in point to rotate the car through the apex.',
    body: `Trail braking means you don't finish all your braking in a straight line. Instead, you carry a decreasing amount of brake pressure as you turn in, releasing it progressively through the corner entry.\n\nThis shifts weight to the front tires, increasing their grip and allowing the rear to rotate — giving you a tighter, faster line through the corner.`,
    pillar: 'racing',
    relatedConceptIds: ['c-weight-transfer', 'c-understeer', 'c-apex'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-weight-transfer',
    slug: 'weight-transfer',
    title: 'Weight Transfer',
    summary: 'How a car\'s weight shifts under acceleration, braking, and cornering forces.',
    body: `Every time you brake, accelerate, or turn, the car's weight shifts. Braking pushes weight forward, acceleration pushes it back, and cornering pushes it to the outside.\n\nUnderstanding weight transfer lets you predict how much grip each tire has at any moment — which is the foundation of fast, consistent driving.`,
    pillar: 'racing',
    relatedConceptIds: ['c-trail-braking', 'c-oversteer', 'c-understeer'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-apex',
    slug: 'apex',
    title: 'Apex',
    summary: 'The innermost point of a corner — where the car gets closest to the inside edge.',
    body: `The apex is the geometric midpoint of your corner. Hit it right and you've used the full width of the track, straightened the line, and kept your speed up.\n\nThere are early, late, and geometric apexes — each with different uses. Late apexes are more common in sim racing because they let you get back to full throttle sooner.`,
    pillar: 'racing',
    relatedConceptIds: ['c-trail-braking', 'c-weight-transfer'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-oversteer',
    slug: 'oversteer',
    title: 'Oversteer',
    summary: 'When the rear of the car loses grip and rotates more than the front.',
    body: `Oversteer happens when the rear tires lose traction relative to the front. The car rotates past the intended line — the tail steps out.\n\nCan be caused by too much throttle on corner exit, lifting off mid-corner, or a car setup that's rear-heavy. In moderation it's useful for rotating the car. Too much and you're spinning.`,
    pillar: 'racing',
    relatedConceptIds: ['c-understeer', 'c-weight-transfer'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-understeer',
    slug: 'understeer',
    title: 'Understeer',
    summary: 'When the front tires lose grip and the car pushes wide of the intended line.',
    body: `Understeer is when the front tires can't provide the turning force needed. The car goes straight when you want to turn — it "pushes" wide.\n\nCommon causes: too much speed into a corner, too early on the throttle, or a front-heavy setup. The fix is usually braking earlier, carrying less speed, or adjusting front aero/suspension.`,
    pillar: 'racing',
    relatedConceptIds: ['c-oversteer', 'c-weight-transfer'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-brake-bias',
    slug: 'brake-bias',
    title: 'Brake Bias',
    summary: 'The front-to-rear split of braking force — a key setup adjustment in most race cars.',
    body: `Brake bias controls how much braking force goes to the front vs. rear axle. More forward bias helps rotation on entry; more rearward bias adds stability but can reduce rotation.\n\nIn sim racing it's often adjustable on the fly and is one of the most impactful in-lap adjustments you can make.`,
    pillar: 'car',
    relatedConceptIds: ['c-weight-transfer', 'c-trail-braking'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-differential',
    slug: 'differential',
    title: 'Differential',
    summary: 'Allows driven wheels to rotate at different speeds — critical for cornering traction.',
    body: `A differential lets the inside and outside driven wheels turn at different speeds when cornering. Without it, one wheel would have to scrub or skip.\n\nIn racing, the diff settings (preload, power ramp, coast ramp) affect how the car rotates on entry, mid-corner, and on throttle exit.`,
    pillar: 'car',
    relatedConceptIds: ['c-oversteer', 'c-weight-transfer'],
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'c-tire-temperature',
    slug: 'tire-temperature',
    title: 'Tire Temperature',
    summary: 'Tires operate in a specific temperature window — outside it, grip drops significantly.',
    body: `Each tire compound has an optimal temperature range where it provides maximum grip. Too cold and the rubber is hard and slippery. Too hot and it degrades rapidly.\n\nManaging tire temps involves managing how hard you push, how you brake, and how setup affects load distribution.`,
    pillar: 'car',
    relatedConceptIds: ['c-brake-bias', 'c-weight-transfer'],
    createdAt: '2026-01-01T00:00:00Z',
  },
]

// ─── Lessons ──────────────────────────────────────────────────────────────────

export const MOCK_LESSONS: Lesson[] = [
  {
    id: 'l-trail-braking',
    slug: 'trail-braking',
    title: 'Trail Braking',
    summary: 'How carrying brake pressure past turn-in makes you faster through every corner.',
    pillar: 'racing',
    category: 'braking',
    difficulty: 'intermediate',
    keyTakeaways: [
      'Trail braking means decreasing brake pressure as you turn in — not slamming then releasing',
      'It loads the front tires, increasing grip exactly when you need rotation',
      'The release point is the skill — earlier than you think, smoother than you expect',
      'Works on every type of corner; the technique scales, the timing changes',
    ],
    body: '',
    thumbnailColor: '#1A1A1A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    emoji: '🛑',
    conceptIds: ['c-trail-braking', 'c-weight-transfer', 'c-apex'],
    diagramIds: [],
    relatedLessonIds: ['l-overtaking', 'l-defense'],
    moduleId: 'mod-racecraft',
    publishedAt: '2026-01-10T00:00:00Z',
    createdAt: '2026-01-01T00:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l-overtaking',
    slug: 'overtaking',
    title: 'Overtaking',
    summary: 'How to set up, commit to, and complete a clean pass without giving the position back.',
    pillar: 'racing',
    category: 'overtaking',
    difficulty: 'intermediate',
    keyTakeaways: [
      'Get alongside before the braking zone — don\'t dive bomb from three car lengths back',
      'Out-brake, don\'t out-maneuver — late braking beats a lunge every time',
      'Protect the exit: make the move mean something by being first to throttle',
      'In sim, the physics are honest — if you hit them, it\'s your fault',
    ],
    body: '',
    thumbnailColor: '#1A0A0A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80',
    emoji: '⚡',
    conceptIds: ['c-apex', 'c-weight-transfer'],
    diagramIds: [],
    relatedLessonIds: ['l-trail-braking', 'l-defense'],
    moduleId: 'mod-racecraft',
    publishedAt: '2026-01-12T00:00:00Z',
    createdAt: '2026-01-02T00:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l-defense',
    slug: 'defense',
    title: 'Letting Drivers Past & Defense',
    summary: 'When to defend your position, when to let someone through, and how to do both cleanly.',
    pillar: 'racing',
    category: 'defense',
    difficulty: 'beginner',
    keyTakeaways: [
      'One move to defend — block twice and you\'re the problem driver on the server',
      'Blue flags exist for a reason: let the faster car through without a fight',
      'Cover the inside line early — don\'t leave the door open then close it late',
      'The best defense is a gap — if they can\'t get close, they can\'t overtake',
    ],
    body: '',
    thumbnailColor: '#0A0A1A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=800&q=80',
    emoji: '🛡️',
    conceptIds: ['c-apex'],
    diagramIds: [],
    relatedLessonIds: ['l-overtaking', 'l-trail-braking'],
    moduleId: 'mod-racecraft',
    publishedAt: '2026-01-15T00:00:00Z',
    createdAt: '2026-01-03T00:00:00Z',
    isFeatured: false,
  },
  {
    id: 'l-suspension',
    slug: 'suspension',
    title: 'How Suspension Works',
    summary: 'What suspension actually does, why it matters for handling, and how to think about setup.',
    pillar: 'car',
    category: 'suspension',
    difficulty: 'beginner',
    keyTakeaways: [
      'Suspension keeps the tire in contact with the road — that\'s it, that\'s the whole job',
      'Stiffer isn\'t always faster: too stiff and the tire skips over bumps instead of tracking them',
      'Roll stiffness affects how much the car leans in corners — which changes weight transfer',
      'Front vs. rear stiffness balance is one of the biggest handling tuning levers you have',
    ],
    body: '',
    thumbnailColor: '#0A1A0A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80',
    emoji: '🔩',
    conceptIds: ['c-weight-transfer'],
    diagramIds: [],
    relatedLessonIds: ['l-brake-balance', 'l-tire-temperature'],
    moduleId: 'mod-car-systems',
    publishedAt: '2026-01-20T00:00:00Z',
    createdAt: '2026-01-10T00:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l-brake-balance',
    slug: 'brake-balance',
    title: 'Brake Balance',
    summary: 'Understanding front-to-rear brake bias and how it shapes corner entry.',
    pillar: 'car',
    category: 'brakes',
    difficulty: 'intermediate',
    keyTakeaways: [
      'More front bias = more rotation on entry but risks front lock-up',
      'More rear bias = more stability but less rotation — good for high-speed corners',
      'Adjust it lap by lap as tires wear and fuel burns off',
      'In most sims, brake bias is your most impactful in-car adjustment',
    ],
    body: '',
    thumbnailColor: '#1A0A00',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    emoji: '🏎️',
    conceptIds: ['c-brake-bias', 'c-weight-transfer'],
    diagramIds: [],
    relatedLessonIds: ['l-suspension', 'l-trail-braking'],
    moduleId: 'mod-car-systems',
    publishedAt: '2026-01-22T00:00:00Z',
    createdAt: '2026-01-11T00:00:00Z',
    isFeatured: false,
  },
  {
    id: 'l-differential',
    slug: 'differential',
    title: 'The Differential',
    summary: 'What a diff does, why there are different types, and what the settings actually change.',
    pillar: 'car',
    category: 'drivetrain',
    difficulty: 'advanced',
    keyTakeaways: [
      'The diff lets driven wheels rotate at different speeds — essential for cornering',
      'A locked diff gives traction but kills rotation; open diff gives rotation but loses traction',
      'Power ramp controls how the diff locks under throttle — affects exit oversteer',
      'Coast ramp controls how it locks under engine braking — affects entry rotation',
    ],
    body: '',
    thumbnailColor: '#0A0A0A',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80',
    emoji: '⚙️',
    conceptIds: ['c-differential', 'c-oversteer'],
    diagramIds: [],
    relatedLessonIds: ['l-suspension', 'l-brake-balance'],
    moduleId: 'mod-car-systems',
    publishedAt: '2026-01-25T00:00:00Z',
    createdAt: '2026-01-12T00:00:00Z',
    isFeatured: false,
  },
  {
    id: 'l-tire-temperature',
    slug: 'tire-temperature',
    title: 'Tire Temperature & Management',
    summary: 'Why tires have a temperature window, and how to keep them in it.',
    pillar: 'car',
    category: 'tires',
    difficulty: 'intermediate',
    keyTakeaways: [
      'Every compound has a temp window — outside it, grip drops fast',
      'Overheating tires is often worse than cold tires: the damage is faster and longer lasting',
      'Brake bias, driving style, and setup all affect where heat builds up',
      'In endurance racing, tire management IS the race strategy',
    ],
    body: '',
    thumbnailColor: '#1A0800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
    emoji: '🌡️',
    conceptIds: ['c-tire-temperature', 'c-brake-bias'],
    diagramIds: [],
    relatedLessonIds: ['l-brake-balance', 'l-suspension'],
    moduleId: 'mod-car-systems',
    publishedAt: '2026-01-28T00:00:00Z',
    createdAt: '2026-01-13T00:00:00Z',
    isFeatured: false,
  },
]

// ─── Modules ──────────────────────────────────────────────────────────────────

export const MOCK_MODULES: Module[] = [
  {
    id: 'mod-racecraft',
    slug: 'racecraft',
    title: 'Racecraft Fundamentals',
    description: 'The techniques and decisions that separate fast laps from race wins.',
    pillar: 'racing',
    lessonIds: ['l-trail-braking', 'l-overtaking', 'l-defense'],
    emoji: '🏁',
    color: '#E8322A',
  },
  {
    id: 'mod-car-systems',
    slug: 'car-systems',
    title: 'Car Systems',
    description: 'How the mechanical pieces work together — and what to do when they don\'t.',
    pillar: 'car',
    lessonIds: ['l-suspension', 'l-brake-balance', 'l-differential', 'l-tire-temperature'],
    emoji: '🔧',
    color: '#4A9EDB',
  },
]

// ─── Quizzes ──────────────────────────────────────────────────────────────────

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: 'q-trail-braking',
    lessonId: 'l-trail-braking',
    title: 'Trail Braking Quiz',
    questions: [
      {
        id: 'q1',
        question: 'What does trail braking primarily do to the car\'s balance?',
        options: [
          'Transfers weight to the rear, increasing rear grip',
          'Transfers weight to the front, increasing front grip and rotation',
          'Evenly distributes weight across all four tires',
          'Reduces overall grip to help the car slide',
        ],
        correctIndex: 1,
        explanation: 'Trail braking carries brake pressure past turn-in, which keeps weight on the front tires. This increases front grip and allows the rear to rotate — which is exactly what you want for a tight, fast line.',
      },
      {
        id: 'q2',
        question: 'When should you finish releasing the brakes during trail braking?',
        options: [
          'Before turn-in',
          'At the apex',
          'Progressively through corner entry, fully released around the apex',
          'After the apex on corner exit',
        ],
        correctIndex: 2,
        explanation: 'The brake release is progressive — you\'re carrying decreasing pressure as you turn in, with full release coming around the apex. This keeps the front loaded throughout entry.',
      },
      {
        id: 'q3',
        question: 'Trail braking too aggressively (holding too much brake too late) is most likely to cause:',
        options: [
          'Understeer on exit',
          'The front tires to lock and the car to go straight',
          'Oversteer mid-corner as the rear loses grip',
          'No effect — more brake pressure is always better',
        ],
        correctIndex: 2,
        explanation: 'Too much trail braking loads the front heavily and unloads the rear. The rear tires lose grip and step out — mid-corner oversteer. This is why the technique requires a precise, progressive release.',
      },
    ],
  },
  {
    id: 'q-brake-balance',
    lessonId: 'l-brake-balance',
    title: 'Brake Balance Quiz',
    questions: [
      {
        id: 'q1',
        question: 'Moving brake bias toward the front will:',
        options: [
          'Make the car more stable under braking with less rotation',
          'Increase entry rotation but risk front wheel lock-up',
          'Have no effect on handling — only affects stopping distance',
          'Always improve lap time regardless of conditions',
        ],
        correctIndex: 1,
        explanation: 'More front bias loads the front tires harder under braking, which increases rotation but also brings the front lock-up threshold closer. It\'s a balance between rotation and stability.',
      },
      {
        id: 'q2',
        question: 'As tire wear increases over a stint, you typically want to:',
        options: [
          'Keep brake bias exactly the same throughout',
          'Move bias toward the rear to compensate for reduced front grip',
          'Increase front bias because worn tires need more force',
          'Switch to full rear braking to protect the fronts',
        ],
        correctIndex: 1,
        explanation: 'As fronts wear and lose grip, they\'ll lock up more easily. Moving bias rearward compensates — it reduces the load on the degraded fronts and keeps the balance stable.',
      },
    ],
  },
]
